apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-dev
  namespace: openshift-gitops
spec:
  project: development
  source:
    repoURL: https://github.com/Saurabh-tcs/argocd-app-of-apps-helm.git
    targetRevision: ee3fff6
    path: charts/apps
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
